"""Add index to LogActividad.fecha for performance

Revision ID: 22f0a12fed1c
Revises: 
Create Date: 2025-12-16 22:49:16.278298

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '22f0a12fed1c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('log_actividad', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_log_actividad_fecha'), ['fecha'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('log_actividad', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_log_actividad_fecha'))

    # ### end Alembic commands ###
