"""Add soft delete to Articulo model

Revision ID: 87448cfe23d1
Revises: 22f0a12fed1c
Create Date: 2025-12-16 23:37:13.869682

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '87448cfe23d1'
down_revision = '22f0a12fed1c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('articulo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deleted_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('articulo', schema=None) as batch_op:
        batch_op.drop_column('deleted_at')

    # ### end Alembic commands ###
