"""Add descripcion and updated_at to Articulo

Revision ID: fac21c9d99b2
Revises: 87448cfe23d1
Create Date: 2025-12-19 02:28:05.118608

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fac21c9d99b2'
down_revision = '87448cfe23d1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('articulo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('descripcion', sa.String(length=300), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))
        batch_op.create_index(batch_op.f('ix_articulo_updated_at'), ['updated_at'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('articulo', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_articulo_updated_at'))
        batch_op.drop_column('updated_at')
        batch_op.drop_column('descripcion')

    # ### end Alembic commands ###
